# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 09:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text_short',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
